### ISSUE TITLE
Error when running `npm start`

### ISSUE THREAD

**Issue by hyakurendev** [Bdragon93/hyakusenrenma-cards#1]
<img width="903" alt="screen shot 2017-11-06 at 6 18 52 pm" src="https://user-images.githubusercontent.com/33084402/32433642-04e5efdc-c31f-11e7-9263-0150c227aacb.png">

`react-redux` component is missing

**Comment by Bdragon93** [comment]
Oh, I am so sorry, I fixed.
Thank you!
